name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: PHP ${{ matrix.php-versions }} - Laravel 11
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
    env:
      extensions: redis, xdebug
      cache-key: v0.1.0
    services:
      mysql:
        image: mysql:8.4.0
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Setup cache environment
    #   id: extcache
    #   uses: shivammathur/cache-extensions@v1
    #   with:
    #     php-version: ${{ matrix.php-versions }}
    #     extensions: ${{ env.extensions }}
    #     key: ${{ env.cache-key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }}

    # - name: Cache extensions
    #   uses: actions/cache@v4
    #   with:
    #     path: ${{ steps.extcache.outputs.dir }}
    #     key: ${{ steps.extcache.outputs.key }}
    #     restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup app key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Migrate Database
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
